### ISSUE TITLE
unpack.sh can't be found

### ISSUE THREAD

**Issue by Jas0n0ss** [gngpp/xunlei#122]
when I clone this repo try to build on my own with this guide https://github.com/gngpp/xunlei#%E8%87%AA%E8%A1%8C%E7%BC%96%E8%AF%91

there is `unpack.sh` mentioned while I didn't see this sh file in source code, would u please update it , much appreciated.
```
[root@homesrv /mnt/xunlei]# sh build.sh
bash: unpack.sh: No such file or directory
```

**Comment by gngpp** [comment]
I have deleted it, you can find it in the previous tag version, or commit record
