### ISSUE TITLE
[Bug] 打开控制台产生大量僵尸进程

### ISSUE THREAD

**Issue by f0re1gnKey** [gngpp/xunlei#126]
打开位于5055的控制台后，关闭网页，使用ps -ef查询系统进程，会出现僵尸进程。浏览控制台越多，僵尸进程越多。
系统debian12
`root         440     383  0 06:44 ?        00:00:00 [xunlei-pan-cli-] <defunct>`

**Comment by gngpp** [comment]
这是迅雷的子进程，我也搞不明白为什么跑这么多

**Comment by gngpp** [comment]
https://github.com/gngpp/thunder/releases/tag/v1.0.0
