### ISSUE TITLE
How to build xunlei-embed?

### ISSUE THREAD

**Issue by leiless** [gngpp/xunlei#127]
请教下需要如何构建 `xunlei-embed`（离线安装包）？

**Comment by gngpp** [comment]
现在不支持，等后面更新，可以根据安装包进行安装，不需要从头编译

**Comment by leiless** [comment]
抱歉，我没理解，目前 Releases 里面的 `xunlei-embed-*` 是如何完成编译的呢？

**Comment by gngpp** [comment]
下载解压迅雷包，嵌入二进制，现在已经不支持了

**Comment by leiless** [comment]
感谢！理解了，看起来是手动嵌入的迅雷的程序包然后再打包上传到的Releases。
