### ISSUE TITLE
X86小插件显示启动失败

### ISSUE THREAD

**Issue by xcf13363175** [gngpp/xunlei#34]
X86小插件显示启动失败

**Comment by xcf13363175** [comment]
X86小插件显示启动失败
![image](https://github.com/gngpp/nas-xunlei/assets/28884815/c707df91-2031-429b-b736-bffccd474a1c)

**Comment by gngpp** [comment]
> X86小插件显示启动失败
> ![image](https://github.com/gngpp/nas-xunlei/assets/28884815/c707df91-2031-429b-b736-bffccd474a1c)
> 

系统是不是没有bash，需要安装bash

**Comment by xcf13363175** [comment]
有bash的，大雕打包的固件。

**Comment by gngpp** [comment]
> 有bash的，大雕打包的固件。

那个固件？发出来我看看
