### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by OldCoding** [gngpp/xunlei#49]
配置后显示运行，但无法正常访问管理页面，页面是白屏的，什么内容都没有，设备是x96Max+，固件是immortalwrt源码编译
![屏幕截图 2023-05-19 122923](https://github.com/gngpp/xunlei/assets/85047508/c158d268-f89d-4c59-9b11-63e11d25de18)
日志
![屏幕截图 2023-05-19 122742](https://github.com/gngpp/xunlei/assets/85047508/1bf02bab-b836-48dc-8d0d-5f15cd7c9516)
INFO 2023-05-19 12:27:14: [Asset] LD_LIBRARY_PATH=/var/packages/pan-xunlei-com/target/host/lib
INFO 2023-05-19 12:27:14: [XunleiBackendServer] Mount /opt/xunlei/downloads to /xunlei succeeded
INFO 2023-05-19 12:27:14: [XunleiLauncher] Start Xunlei Pannel UI, listening on 192.168.10.2:5055
INFO 2023-05-19 12:27:14: [XunleiBackendServer] Start Xunlei Backend Server
INFO 2023-05-19 12:27:14: [XunleiBackendServer] Xunlei Backend Server PID: 30300
/var/packages/pan-xunlei-com/target/xunlei-pan-cli-launcher.arm64: symbol lookup error: /var/packages/pan-xunlei-com/target/host/lib/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
2023-05-19 04:27:21.841932 UTC - GET / - 98.8us - 307
/var/packages/pan-xunlei-com/target/xunlei-pan-cli-web: symbol lookup error: /var/packages/pan-xunlei-com/target/host/lib/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
2023-05-19 04:27:21.856902 UTC - GET /webman/3rdparty/pan-xunlei-com/index.cgi/ - 3.9ms - 200
/var/packages/pan-xunlei-com/target/xunlei-pan-cli-web: symbol lookup error: /var/packages/pan-xunlei-com/target/host/lib/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
2023-05-19 04:27:21.969276 UTC - GET /favicon.ico - 3.2ms - 200
2023-05-19 04:28:31.088958 UTC - GET / - 103.4us - 307
/var/packages/pan-xunlei-com/target/xunlei-pan-cli-web: symbol lookup error: /var/packages/pan-xunlei-com/target/host/lib/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
2023-05-19 04:28:31.101185 UTC - GET /webman/3rdparty/pan-xunlei-com/index.cgi/ - 3.8ms - 200
/var/packages/pan-xunlei-com/target/xunlei-pan-cli-web: symbol lookup error: /var/packages/pan-xunlei-com/target/host/lib/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
2023-05-19 04:28:31.199904 UTC - GET /favicon.ico - 3.2ms - 200

**Comment by gngpp** [comment]
看样子是库兼容问题，immoralwrt那个版本

**Comment by OldCoding** [comment]
@gngpp 用的master分支

**Comment by gngpp** [comment]
能否给我远程看看，口头不好调试联系发我邮箱gngppz@gmail.com

**Comment by gngpp** [comment]
> 能否给我远程看看，口头不好调试联系发我邮箱[gngppz@gmail.com](mailto:gngppz@gmail.com)

或者你有公网可以暂时开个端口给我

**Comment by OldCoding** [comment]
> > 能否给我远程看看，口头不好调试联系发我邮箱[gngppz@gmail.com](mailto:gngppz@gmail.com)
> 
> 或者你有公网可以暂时开个端口给我

没有公网，咋远程

**Comment by gngpp** [comment]
> > > 能否给我远程看看，口头不好调试联系发我邮箱[gngppz@gmail.com](mailto:gngppz@gmail.com)
> > 
> > 
> > 或者你有公网可以暂时开个端口给我
> 
> 没有公网，咋远程

桌面远程
