### ISSUE TITLE
x86_64一直打log 停不下来

### ISSUE THREAD

**Issue by shilongfei** [gngpp/xunlei#54]
x86_64一直打log 停不下来
![image](https://github.com/gngpp/xunlei/assets/4022990/979cb9d1-d2ed-4fd9-8331-b4abda9d8263)

**Comment by gngpp** [comment]
> x86_64一直打log 停不下来
> ![image](https://github.com/gngpp/xunlei/assets/4022990/979cb9d1-d2ed-4fd9-8331-b4abda9d8263)
> 

log是正常的，只要有操作或者打开页面就会打log，是为了方便诊断问题
