### ISSUE TITLE
N1，openwrt运行不起来

### ISSUE THREAD

**Issue by repairer7** [gngpp/xunlei#64]
报错日志如下
DEBUG 2023-06-01 15:15:59: [Asset] ldd --version stdout: musl libc (aarch64)
Version 1.2.3
Dynamic Program Loader
Usage: ldd [options] [--] pathname

DEBUG 2023-06-01 15:15:59: [Asset] Run on musl environment
Error: [Asset] Failed to create directory: /var/packages/pan-xunlei-com/target/host/lib

Caused by:
    No such file or directory (os error 2)
DEBUG 2023-06-01 15:16:03: [Asset] ldd --version stdout: musl libc (aarch64)
Version 1.2.3
Dynamic Program Loader
Usage: ldd [options] [--] pathname

DEBUG 2023-06-01 15:16:03: [Asset] Run on musl environment
Error: [Asset] Failed to create directory: /var/packages/pan-xunlei-com/target/host/lib

Caused by:
    No such file or directory (os error 2)

**Comment by gngpp** [comment]
https://github.com/gngpp/xunlei/actions/runs/5141971186,等编译完，你就卸载重装吧

**Comment by repairer7** [comment]
可以运行，但进入管理页面并登陆后无页面
06/01 17:20:05.78 ERROR [panCliPid=19041]Launcher.startVersion cmd.Run exit error err:exit status 127 panCliPath:/opt/xunlei/.drive/bin/xunlei-pan-cli.3.7.1.arm64 StdErr: repErr:exit status 127
06/01 17:20:05.78 ERROR start new version 3.7.1=>3.7.1 err:exit status 127
06/01 17:20:05.78 WARNING launcher version error exit status 127 retry 2
06/01 17:20:05.78 INFO write launcher pid to file /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid 18696
06/01 17:20:06.38 ERROR [report=true&panCliPid=19041]CheckProcess Signal err:os: process already finished
06/01 17:20:16.05 INFO filter not match { false map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["client_version","notIn","0"]}]}] []} map[hour:17]
06/01 17:20:16.05 INFO filter not match { false map[] map[] map[] <nil> null [{"match":["platform","in","synology"]} {"matchAny":[{"match":["client_version","notIn","0"]},{"match":["user_id","in","190725001","284819250"]},{"match":["user_id","in","757330327","743061244","190725001","152691506","228546131","284819224","272632280","284819047","766616264"]}]}] []} map[hour:17]
06/01 17:20:16.05 INFO filter not match { false map[] map[] map[] <nil> null [{"match":["platform","in","synology"]} {"match":["hour","in","2","3","4","5"]} {"matchAny":[{"match":["client_version","notIn","0"]}]}] []} map[hour:17]
06/01 17:20:16.05 INFO get version list [] map[hour:17]

**Comment by repairer7** [comment]
ip:5055/webman/3rdparty/pan-xunlei-com/index.cgi/

**Comment by gngpp** [comment]
重启，真是奇怪，一直没遇过这种问题
