### ISSUE TITLE
x86，首次安装无法运行

### ISSUE THREAD

**Issue by markvlenvision** [gngpp/xunlei#70]
x86虚拟机下lede的openwrt，首次安装无法运行，开启后等一两秒自动关闭。且无日志输出。
安装方式
`wget https://github.com/gngpp/xunlei/releases/download/v3.8.0-23/xunlei_3.8.0-23_x86_64.ipk
wget https://github.com/gngpp/xunlei/releases/download/v3.8.0-23/luci-app-xunlei_1.0.1-8-1_all.ipk
wget https://github.com/gngpp/xunlei/releases/download/v3.8.0-23/luci-i18n-xunlei-zh-cn_1.0.1-8-1_all.ipk

opkg install xunlei_3.8.0-23_x86_64.ipk
opkg install luci-app-xunlei_1.0.1-8-1_all.ipk
opkg install luci-i18n-xunlei-zh-cn_1.0.1-8-1_all.ipk`

翻阅 closed issue 中案例，卸载重新安装，
执行
`service xunlei disable && service xunlei enable`
重启，即可运行。

希望可以更新到readme文件

**Comment by gngpp** [comment]
> x86虚拟机下lede的openwrt，首次安装无法运行，开启后等一两秒自动关闭。且无日志输出。 安装方式 `wget https://github.com/gngpp/xunlei/releases/download/v3.8.0-23/xunlei_3.8.0-23_x86_64.ipk wget https://github.com/gngpp/xunlei/releases/download/v3.8.0-23/luci-app-xunlei_1.0.1-8-1_all.ipk wget https://github.com/gngpp/xunlei/releases/download/v3.8.0-23/luci-i18n-xunlei-zh-cn_1.0.1-8-1_all.ipk
> 
> opkg install xunlei_3.8.0-23_x86_64.ipk opkg install luci-app-xunlei_1.0.1-8-1_all.ipk opkg install luci-i18n-xunlei-zh-cn_1.0.1-8-1_all.ipk`
> 
> 翻阅 closed issue 中案例，卸载重新安装， 执行 `service xunlei disable && service xunlei enable` 重启，即可运行。
> 
> 希望可以更新到readme文件

控制台可以开debug模式的，第一次安装应该是没问题的（可能没有执行uci-defaults那个脚本，重启就会执行，或者手动执行一次），我自己集成编译进固件用了很久

**Comment by homeyone** [comment]
我也遇到了这个问题，系统都重启了也不行。我用的固件是[Powered by LuCI Master (git-23.141.16773-28dd4b3)](https://github.com/openwrt/luci) / [ArgonTheme v1.8.1](https://github.com/jerrykuku/luci-theme-argon) / Compiled on Jun.10,2023 @ OpenWrt R23.6.6

**Comment by gngpp** [comment]
> 我也遇到了这个问题，系统都重启了也不行。我用的固件是[Powered by LuCI Master (git-23.141.16773-28dd4b3)](https://github.com/openwrt/luci) / [ArgonTheme v1.8.1](https://github.com/jerrykuku/luci-theme-argon) / Compiled on Jun.10,2023 @ OpenWrt R23.6.6

这要看你的系统是不是是不是自带了glibc，再或者也没看见日志，启动不行肯定有日志
