### ISSUE TITLE
任何按钮都点击没有窗口

### ISSUE THREAD

**Issue by 277383761** [gngpp/xunlei#80]
并提示
![image](https://github.com/gngpp/xunlei/assets/49450669/24709395-3974-4d60-ad1f-944c3c4a226c)
![image](https://github.com/gngpp/xunlei/assets/49450669/2672c847-e3bd-4d12-9b2f-86eb9629fc3e)

**Comment by 277383761** [comment]
设备校验失败,请重新登录设备或刷新：undefined syno_ unauthorised 群晖登录态校验失败exit status 12

**Comment by 277383761** [comment]
在192.168.1.1:5055这个web界面按任何按钮都会使整个界面变灰，但没弹窗。意思就是没法用

**Comment by 277383761** [comment]
3.8.0-25

**Comment by PandaEgg** [comment]
3.8.0-25这个版本好像有问题。全部卸载后安装3.8.0-24就可以了
