### ISSUE TITLE
systemctl版本会以root用户下载文件，影响访问权限

### ISSUE THREAD

**Issue by chevy222** [gngpp/xunlei#86]
systemctl版本会以root用户下载文件，影响访问权限，希望可以指定用户运行。

**Comment by gngpp** [comment]
你来pr一下吧，加两个参数就行了

**Comment by chevy222** [comment]
> 你来pr一下吧，加两个参数就行了

大佬，别开玩笑了，我敲过了，不行，还是要你来。

**Comment by chevy222** [comment]
> 你来pr一下吧，加两个参数就行了

会报
`[XunleiBackendServer] error: [XunleiBackendServer] Mount /home/chevy/xunleidownload to /xunlei failed`
大佬，请帮忙。

**Comment by gngpp** [comment]
> 没有权限捏，要挂载目录权限

![image](https://github.com/gngpp/xunlei/assets/51810656/5273cdc0-c134-45da-b177-7895b15bb955)

**Comment by chevy222** [comment]
我说的是systemctl版本哦，不是docker，就是说我要根目录建一个/xunlei目录？

**Comment by gngpp** [comment]
> > 没有权限捏，要挂载目录权限
> 
> ![image](https://user-images.githubusercontent.com/51810656/254177967-5273cdc0-c134-45da-b177-7895b15bb955.png)

迅雷有点二逼，所以需要挂载点模拟识别硬盘，不然是识别不到有些硬盘挂载目录的，这样模拟群晖硬盘挂载而已。

**Comment by gngpp** [comment]
> 我说的是systemctl版本哦，不是docker，就是说我要根目录建一个/xunlei目录？

是的，你可以手动创建试试

**Comment by gngpp** [comment]
除了创建权限，还有挂载权限，创建目录我觉得可以加个启动参数，来自定义指定目录（假如存在就不用创建了）。今晚有空看看吧

**Comment by gngpp** [comment]
`-m, --mount-bind-download-path <MOUNT_BIND_DOWNLOAD_PATH> Xunlei mount bind download directory [default: /xunlei]`
这个参数，你改一下存在的目录就行了，不然默认创建

**Comment by chevy222** [comment]
> 除了创建权限，还有挂载权限，创建目录我觉得可以加个启动参数，来自定义指定目录（假如存在就不用创建了）。今晚有空看看吧

感谢感谢，之前有研究过cnk3x的，最后还是不行，望大神晚上研究一下

**Comment by gngpp** [comment]
<img width="1093" alt="image" src="https://github.com/gngpp/xunlei/assets/51810656/953181c1-ea75-4173-9cf6-62e4d483e36a">
这样应该可以了吧，下载的文件是所属uid，gid的用户，不过执行依旧需要root，但不影响下载文件权限

**Comment by gngpp** [comment]
gid uid都支持，你看到的root是用户组，我这个用户本身就在root

**Comment by chevy222** [comment]
发个releases呗，我帮你验证一下。

**Comment by gngpp** [comment]
![image](https://github.com/gngpp/xunlei/assets/51810656/02d7018a-dace-48c1-8c08-b4cba5660afa)

https://github.com/gngpp/xunlei/actions/runs/5605748037

**Comment by chevy222** [comment]
这个-U不会和原来那个 登录的用户名冲突吗？-U, --auth-user <AUTH_USER>  Xunlei authentication username

**Comment by gngpp** [comment]
不冲突，我已经改了，需要长参数

**Comment by chevy222** [comment]
哦哦，看到了，以readme.md为准。
